services:
  blazor-client:
    image: thejoun/blazor-client
    build:
      context: .
      dockerfile: BlazorClient/Dockerfile
    ports:
      - 5000:5000
    domainname: pisproject
    environment:
      - USER_TIMELINE_SERVICE=http://pisproject.eastus.azurecontainer.io:5001
      - USER_PROFILE_SERVICE=http://pisproject.eastus.azurecontainer.io:5002
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
  user-timeline-service:
    image: thejoun/user-timeline-service
    build: 
      context: .
      dockerfile: UserTimelineService/Dockerfile
    ports:
      - 5001:5001
    domainname: pisproject
    environment:
      - ConnectionStrings__Default=Server=pismysqlserv.mysql.database.azure.com;Uid=Admin123;Pwd=Password123!;Database=twittercopy
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
  user-profile-service:
    image: thejoun/user-profile-service
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    ports:
      - 5002:5002
    domainname: pisproject
    environment:
      - ConnectionStrings__Default=Server=pismysqlserv.mysql.database.azure.com;Uid=Admin123;Pwd=Password123!;Database=twittercopy
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G