services:
  blazor-client:
    image: thejoun/blazor-client
    build:
      context: .
      dockerfile: BlazorClient/Dockerfile-prod
    ports:
      - 80:80
    domainname: pisproject
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 0.1G
  user-timeline-service:
    image: thejoun/user-timeline-service
    build: 
      context: .
      dockerfile: UserTimelineService/Dockerfile
    ports:
      - 5001:5001
    domainname: pisproject
    environment:
      - ConnectionStrings__Default=Server=pismysqlserv.mysql.database.azure.com;Uid=Admin123;Pwd=Password123!;Database=twittercopy
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 0.1G
  user-profile-service:
    image: thejoun/user-profile-service
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    ports:
      - 5002:5002
    domainname: pisproject
    environment:
      - ConnectionStrings__Default=Server=pismysqlserv.mysql.database.azure.com;Uid=Admin123;Pwd=Password123!;Database=twittercopy
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 0.1G