services:
  blazorstandalone:
    image: blazorstandalone
    build:
      context: BlazorClient
      dockerfile: BlazorClient/Dockerfile
    ports:
      - 5000:80
  usertimelineservice:
    build: 
      context: UserTimelineService
      dockerfile: UserTimelineService/Dockerfile
    ports:
      - 5001:8080