services:
  blazorstandalone:
    image: blazorclient
    build:
      context: BlazorClient
      dockerfile: DockerfileBlazorClient
    ports:
      - 5000:80
  usertimelineservice:
    image: usertimelineservice
    build: 
      context: UserTimelineService
      dockerfile: UserTimelineService/Dockerfile
    ports:
      - 5001:8080
  userprofileservice:
    image: userprofileservice
    build:
      context: UserProfileService
      dockerfile: UserProfileService/Dockerfile
    ports:
      - 5002:8080